
apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  description: Added Public Repositories
  name: rafay-repository-rs-tmpl-test-proj-cakuros
  project: test-proj-cakuros
spec:
  agents:
  - name: eaas-agent-test-proj-cakuros
  contexts:
  - name: rafay-test-proj-cakuros
  provider: terraform
  providerOptions:
    terraform:
      useSystemStateStore: true
      version: 1.4.6
  repositoryOptions:
    branch: main
    directoryPath: terraform/aws/101-caas-eks/terraform/repositories
    name: eaas-repo-test-proj-cakuros
  variables:
  - name: public_repositories
    options:
      description: Public Repositories
      override:
        type: notallowed
      required: true
    value: |-
      {
          "nginx-controller" = {
              type = "Helm"
              endpoint = "https://kubernetes.github.io/ingress-nginx"
          }
          "cert-manager" = {
              type = "Helm"
              endpoint = "https://charts.jetstack.io"
          }
      }
    valueType: hcl
  version: v1
